export function clear(key: any, ...args: any[]): void;
export function executed(key: any): any;
export function exists(key: any): any;
export function pause(key: any): any;
export function paused(key: any): any;
export function pending(key: any): any;
export function remaining(key: any): any;
export function restart(key: any): any;
export function resume(key: any): any;
export function set(...args: any[]): any;
